QTLPreviewers: /Users/yiqingxu/git/GeneRat/QTLPreviewers/src/IMQTLPreviewer.cpp File Reference
IMQTLPreviewer.cpp File Reference
#include "IMQTLPreviewer.h"
Functions
double f (double x, double u, double s2)
void initExpressData (const string fileName, const int sampleNumber, vector< EXPData > &expData, EXPData *u0, EXPData *s0, const bool ifPrintLog=VERBOSE_MODE)
void initChildrenGeneData (const string fileName, const int sampleNumber, const int traitNumber, vector< vector< string > > &data, const bool ifPrintLog=VERBOSE_MODE)
void initParentGeneData (const string fileName, vector< string > &geneData, const int traitNumber, const string parentName, const bool ifPrintLog=VERBOSE_MODE)
void initIntervalData (const string fileName, const int intervalNumber, vector< double > &data, const bool ifPrintLog=VERBOSE_MODE)
string HAB2ab (const string input)
double findGeneCP (const vector< string > geneMatrix, const vector< double > rMatrix, const string find, const bool ifPrintLog=VERBOSE_MODE)
void calculateGP (vector< vector< double > > &gp, const vector< vector< string > > &mk, const string qtlGene, const int sampleSize, const int sampleIndex1, const int sampleIndex2, const vector< string > &geneMatrix, const vector< double > &rMatrix, const bool ifUseShortGeneData=false, const bool ifPrintLog=VERBOSE_MODE)
double calculateLOD (const vector< vector< double > > gp, const int sampleSize, const vector< EXPData > expData, const EXPData u0, const EXPData s0, const EXPData u1, const EXPData u2, const EXPData u3, const EXPData s1, const bool ifPrintLog=VERBOSE_MODE)
void EMCalculate (const vector< vector< double > > &gp, const int sampleSize, const vector< EXPData > expData, const EXPData u0, const EXPData s0, EXPData *u1, EXPData *u2, EXPData *u3, EXPData *s1, const bool ifPrintLog=VERBOSE_MODE)
double calcCross (const bitset< GENE_CP_BIT > geneBit, const double r1, const double r2, const double r=0, const double zeta=1)
void reorderGene (vector< string > &geneMatrix)
int calcGeneCP (vector< string > &geneMatrix, vector< double > &rMatrix, const string f, const string m, const string q, const double r1, const double r2, const double r=0, const double zeta=1, const bool ifReorder=true, const bool ifPrintLog=VERBOSE_MODE)
double intervalQTL (const int currentTrait, const EXPData u0, const EXPData s0, const double length, const double startPoint, const vector< vector< string > > &mk, const vector< EXPData > expData, const int sampleSize, const string f, const string m, const string q, const bool ifUseShortGeneData=false, const bool ifPrintLog=VERBOSE_MODE)
void printHelp (const string fileName)
int mainQTL (int args, char *argv[])
int main (int args, char *argv[])
Function Documentation
double calcCross (const bitset< GENE_CP_BIT > geneBit, const double r1, const double r2, const double r = 0, const double zeta = 1)
计算基因型概率
Parameters
geneBit 基因型的二进制表示，其中1表示大写，0表示小写
r1 左侧重组率
r2 右侧重组率
r 整体重组率，默认为0，通过r1和r2计算
zeta 符合系数，默认为1
Returns
基因型概率
Definition at line 338 of file IMQTLPreviewer.cpp.
References GENE_CP_BIT.
Referenced by calcGeneCP().
int calcGeneCP (vector< string > & geneMatrix, vector< double > & rMatrix, const string f, const string m, const string q, const double r1, const double r2, const double r = 0, const double zeta = 1, const bool ifReorder = true, const bool ifPrintLog = VERBOSE_MODE)
计算基因型条件概率分布全数据
Parameters
geneMatrix 基因型
rMatrix 条件型概率
f 父本基因型
m 母本基因型
q QTL基因型
r1 左侧重组率
r2 右侧重组率
r 整体重组率
zeta 符合系数
ifReorder 是否自动重排基因位顺序，如ba被重排为ab
ifPrintLog 是否打印日志
Returns
成功运行则返回1
Definition at line 395 of file IMQTLPreviewer.cpp.
References calcCross(), GENE_CP_CUT, printGeneCP(), and reorderGene().
Referenced by intervalQTL().
void calculateGP (vector< vector< double > > & gp, const vector< vector< string > > & mk, const string qtlGene, const int sampleSize, const int sampleIndex1, const int sampleIndex2, const vector< string > & geneMatrix, const vector< double > & rMatrix, const bool ifUseShortGeneData = false, const bool ifPrintLog = VERBOSE_MODE)
根据基因型数据统计对应的实际分布概率
Parameters
gp 实际分布概率
mk 基因型数据数组
qtlGene QTL基因的字符串
sampleSize 样本大小
sampleIndex1 样本编号1
sampleIndex2 样本编号2
geneMatrix 基因型
rMatrix 条件型概率
ifUseShortGeneData 是否使用短基因表示
ifPrintLog 是否打印日志
获取亲本的基因型
拼接亲本基因型字符串
计算实际分布概率
Definition at line 172 of file IMQTLPreviewer.cpp.
References findGeneCP(), and HAB2ab().
Referenced by intervalQTL().
double calculateLOD (const vector< vector< double > > gp, const int sampleSize, const vector< EXPData > expData, const EXPData u0, const EXPData s0, const EXPData u1, const EXPData u2, const EXPData u3, const EXPData s1, const bool ifPrintLog = VERBOSE_MODE)
利用LOD计分法计算LOD值
Parameters
gp 实际分布概率
sampleSize 样本大小
expData 表现型数据
s0 表现型的统计量sigima平方
s1
u0 表现型的统计量mu
u1
u2
u3
ifPrintLog 是否打印日志
Returns
LOD计分
Definition at line 222 of file IMQTLPreviewer.cpp.
References f().
Referenced by intervalQTL().
void EMCalculate (const vector< vector< double > > & gp, const int sampleSize, const vector< EXPData > expData, const EXPData u0, const EXPData s0, EXPData * u1, EXPData * u2, EXPData * u3, EXPData * s1, const bool ifPrintLog = VERBOSE_MODE)
利用EM算法迭代计算最大似然估计
Parameters
expData 表现型数据
gp 实际分布概率
sampleSize 样本大小
u0 样本的统计量mu
s0 样本的统计量sigma平方
u1
u2
u3
s1
ifPrintLog 是否打印日志
Definition at line 260 of file IMQTLPreviewer.cpp.
References ACCURACY_REQ, and f().
Referenced by intervalQTL().
double f (double x, double u, double s2)
概率密度函数
Parameters
x 输入
u mu
s2 sigma平方
Returns
Definition at line 31 of file IMQTLPreviewer.cpp.
Referenced by calculateLOD(), and EMCalculate().
double findGeneCP (const vector< string > geneMatrix, const vector< double > rMatrix, const string find, const bool ifPrintLog = VERBOSE_MODE)
查找基因型的条件概率
Parameters
geneMatrix 基因型
rMatrix 基因型概率
find 查找的匹配基因型
ifPrintLog 是否打印日志
Returns
基因型的条件概率
Definition at line 134 of file IMQTLPreviewer.cpp.
References GENE_CP_CUT.
Referenced by calculateGP().
string HAB2ab (const string input)
将HAB型的基因数据转成ab型的基因数据，H-ab，A-aa，B-bb
Parameters
input 输入数据
Returns
转换后的数据
Definition at line 119 of file IMQTLPreviewer.cpp.
Referenced by calculateGP().
void initChildrenGeneData (const string fileName, const int sampleNumber, const int traitNumber, vector< vector< string > > & data, const bool ifPrintLog = VERBOSE_MODE)
初始化样本的基因型数据
Parameters
fileName 样本数据文件的文件名
sampleNumber 样本大小
traitNumber 位点数量
data 数据数组
ifPrintLog 是否打印日志
Definition at line 67 of file IMQTLPreviewer.cpp.
References printChildrenGeneData(), and readFile2Matrix().
Referenced by mainQTL().
void initExpressData (const string fileName, const int sampleNumber, vector< EXPData > & expData, EXPData * u0, EXPData * s0, const bool ifPrintLog = VERBOSE_MODE)
初始化样本的表现型数据
Parameters
fileName 样本数据文件的文件名
sampleNumber 样本大小
expData 数据数组
u0 统计量mu 即平均值
s0 统计量sigma平方 及方差
ifPrintLog 是否打印日志
Definition at line 44 of file IMQTLPreviewer.cpp.
References getAverage(), getVariance(), printExpressData(), and readFile2Vector().
Referenced by mainQTL().
void initIntervalData (const string fileName, const int intervalNumber, vector< double > & data, const bool ifPrintLog = VERBOSE_MODE)
初始化遗传图谱的遗传区间距离数据
Parameters
fileName 区间距离数据文件的文件名
intervalNumber 区间个数
data 区间距离数据
ifPrintLog 是否打印日志
Definition at line 102 of file IMQTLPreviewer.cpp.
References printIntervalData(), and readFile2Vector().
Referenced by mainQTL().
void initParentGeneData (const string fileName, vector< string > & geneData, const int traitNumber, const string parentName, const bool ifPrintLog = VERBOSE_MODE)
初始化亲本的基因型数据
Parameters
fileName 亲本数据文件的文件名
geneData 数据数组
traitNumber 位点数量
parentName 亲本名称
ifPrintLog 是否打印日志
Definition at line 84 of file IMQTLPreviewer.cpp.
References printParentGeneData(), and readFile2Vector().
Referenced by mainQTL().
double intervalQTL (const int currentTrait, const EXPData u0, const EXPData s0, const double length, const double startPoint, const vector< vector< string > > & mk, const vector< EXPData > expData, const int sampleSize, const string f, const string m, const string q, const bool ifUseShortGeneData = false, const bool ifPrintLog = VERBOSE_MODE)
区间QTL分析
Parameters
currentTrait 当前位点序号
u0 统计量mu
s0 统计量sigma平方
length 位点间隔
startPoint 开始位置
mk 位点基因型数据
expData 位点表现型数据
sampleSize 样本大小
f 父本基因型
m 母本基因型
q QTL基因型
ifUseShortGeneData 是否使用短基因表示
ifPrintLog 是否打印日志
Returns
返回LOD值
Definition at line 447 of file IMQTLPreviewer.cpp.
References calcGeneCP(), calculateGP(), calculateLOD(), d2r(), EMCalculate(), and GENE_CP_SIZE.
Referenced by mainQTL().
int main (int args, char * argv[])
Definition at line 595 of file IMQTLPreviewer.cpp.
References getTimeStamp(), and mainQTL().
int mainQTL (int args, char * argv[])
若参数个数为1，为手动模式运行，从操作台读取各个参数。
若参数个树为2，为自动模式，从配置文件读取参数。
参数个数错误，打印帮助。
汇总显示各输入参数
读取表型数据文件，并计算表型数组的均值、方差
初始化基因型数据并读取基因型数据文件
初始化并读取位点距离数据，来源为见书115页
初始化亲本的基因型
逐个位点计算LOD值
按步长推进计算LOD值
Definition at line 485 of file IMQTLPreviewer.cpp.
References initChildrenGeneData(), initExpressData(), initIntervalData(), initParentGeneData(), inputBooleanFromKeyboard(), inputValueFromKeyboard(), intervalQTL(), and printHelp().
Referenced by main().
void printHelp (const string fileName)
打印帮助信息
Parameters
fileName 文件名
Definition at line 481 of file IMQTLPreviewer.cpp.
Referenced by mainQTL().
void reorderGene (vector< string > & geneMatrix)
重排基因位顺序，如ba被重排为ab
Parameters
geneMatrix 基因型数组
Returns
成功运行返回1
Definition at line 372 of file IMQTLPreviewer.cpp.
References reorderStr().
Referenced by calcGeneCP().