QTLPreviewers: /Users/yiqingxu/git/GeneRat/QTLPreviewers/src/IMQTLLogger.cpp File Reference
IMQTLLogger.cpp File Reference
#include "IMQTLLogger.h"
Functions
void initLoggers ()
void haltLoggers ()
void printExpressData (const vector< EXPData > data, const EXPData u0, const EXPData s0)
void printIntervalData (const vector< double > data)
void printChildrenGeneData (const vector< vector< string > > data)
void printParentGeneData (const vector< string > data, const string parentString)
void printGeneCP (const vector< string > &geneMatrix, const vector< double > rMatrix)
Variables
Category & logger = log4cpp::Category::getInstance("rootAppender")
Function Documentation
void haltLoggers ()
Definition at line 23 of file IMQTLLogger.cpp.
Referenced by main().
void initLoggers ()
Definition at line 12 of file IMQTLLogger.cpp.
References f(), and logger.
Referenced by main().
void printChildrenGeneData (const vector< vector< string > > data)
打印样本的基因型数据
Parameters
data 样本基因型数据
Definition at line 50 of file IMQTLLogger.cpp.
References logger.
Referenced by initChildrenGeneData().
void printExpressData (const vector< EXPData > data, const EXPData u0, const EXPData s0)
打印样本的表现型数据
Parameters
data 样本表现型数组
u0 统计量mu
s0 统计量sigma平方
Definition at line 33 of file IMQTLLogger.cpp.
References logger, and printVectorData().
Referenced by initExpressData().
void printGeneCP (const vector< string > & geneMatrix, const vector< double > rMatrix)
打印基因型条件概率分布全数据
Parameters
geneMatrix 基因型
rMatrix 条件概率
前四位为亲代基因型
后二位为子代基因型
Definition at line 77 of file IMQTLLogger.cpp.
References logger.
Referenced by calcGeneCP().
void printIntervalData (const vector< double > data)
打印遗传图谱的遗传区间距离数据
Parameters
data 区间距离数据
Definition at line 42 of file IMQTLLogger.cpp.
References printVectorData().
Referenced by initIntervalData().
void printParentGeneData (const vector< string > data, const string parentString)
打印亲本的基因型数据
Parameters
data 亲本基因型数据
parentString 亲本名称
Definition at line 68 of file IMQTLLogger.cpp.
References printVectorData().
Referenced by initParentGeneData().
Variable Documentation
Category& logger = log4cpp::Category::getInstance("rootAppender")
Definition at line 10 of file IMQTLLogger.cpp.
Referenced by calculateGP(), calculateLOD(), EMCalculate(), findGeneCP(), IMQTLRun(), initExpressData(), initIntervalData(), initLoggers(), initParentGeneData(), intervalQTL(), main(), printChildrenGeneData(), printExpressData(), printGeneCP(), and printVectorData().