QTLPreviewers: /Users/yiqingxu/git/GeneRat/QTLPreviewers/src/IMQTLLogger.h File Reference
IMQTLLogger.h File Reference
#include "QTLUtils.h"
Functions
void printExpressData (const vector< EXPData > data)
void printIntervalData (const vector< double > data)
void printChildrenGeneData (const vector< vector< string > > data)
void printParentGeneData (const vector< string > data, const string parentString)
void printGeneCP (const vector< string > &geneMatrix, const vector< double > rMatrix)
bool initLoggers ()
void haltLoggers ()
Variables
Category & logger
Function Documentation
void haltLoggers ()
关闭日志系统
Definition at line 32 of file IMQTLLogger.cpp.
References logger.
Referenced by mainRun().
bool initLoggers ()
初始化日志系统
Returns
返回是否初始化成功
Definition at line 16 of file IMQTLLogger.cpp.
References f(), and logger.
Referenced by mainRun().
void printChildrenGeneData (const vector< vector< string > > data)
打印样本的基因型数据
Parameters
data 样本基因型数据
Definition at line 57 of file IMQTLLogger.cpp.
References logger.
Referenced by initChildrenGeneData().
void printExpressData (const vector< EXPData > data)
打印样本的表现型数据
Parameters
data 样本表现型数组
Definition at line 41 of file IMQTLLogger.cpp.
References printVectorData().
Referenced by initExpressData().
void printGeneCP (const vector< string > & geneMatrix, const vector< double > rMatrix)
打印基因型条件概率分布全数据
Parameters
geneMatrix 基因型
rMatrix 条件概率
前四位为亲代基因型
后二位为子代基因型
Definition at line 84 of file IMQTLLogger.cpp.
References logger.
Referenced by calcGeneCP().
void printIntervalData (const vector< double > data)
打印遗传图谱的遗传区间距离数据
Parameters
data 区间距离数据
Definition at line 49 of file IMQTLLogger.cpp.
References printVectorData().
Referenced by initIntervalData().
void printParentGeneData (const vector< string > data, const string parentString)
打印亲本的基因型数据
Parameters
data 亲本基因型数据
parentString 亲本名称
Definition at line 75 of file IMQTLLogger.cpp.
References printVectorData().
Referenced by initParentGeneData().
Variable Documentation
Category& logger
Definition at line 10 of file IMQTLLogger.cpp.