QTLPreviewers: /Users/yiqingxu/git/GeneRat/QTLPreviewers/src/QTLUtils.cpp File Reference
QTLUtils.cpp File Reference
#include "QTLUtils.h"
Functions
float getTimeStamp ()
int inputBooleanFromKeyboard (string info)
double d2rHaldane (const double d)
double d2rKosambi (const double d)
double d2r (const double x)
string reorderStr (const string input)
Function Documentation
double d2r (const double x)
作图函数，默认使用Haldane作图函数
Parameters
x 遗传距离
Returns
重组率
Definition at line 52 of file QTLUtils.cpp.
References d2rHaldane().
Referenced by intervalQTL().
double d2rHaldane (const double d)
Haldane作图函数
Parameters
d 遗传距离
Returns
重组率
Definition at line 34 of file QTLUtils.cpp.
Referenced by d2r().
double d2rKosambi (const double d)
Kosambi作图函数
Parameters
d 遗传距离
Returns
重组率
Definition at line 43 of file QTLUtils.cpp.
float getTimeStamp ()
获取系统时间的时间戳
Returns
距离上一个时间戳的时间差，单位毫秒
Definition at line 9 of file QTLUtils.cpp.
References SECOND_TO_MS.
Referenced by main().
int inputBooleanFromKeyboard (string info)
从键盘输入判断值，1为真，0为假
Parameters
info 提示信息
Returns
判断值
Definition at line 21 of file QTLUtils.cpp.
Referenced by mainQTL().
string reorderStr (const string input)
重排一个字符串内字符，如bdcae重排为abcde
Parameters
input 需要重排的字符串
Returns
Definition at line 69 of file QTLUtils.cpp.
Referenced by reorderGene().