QTLPreviewers: /Users/yiqingxu/git/GeneRat/QTLPreviewers/src/QTLUtils.h File Reference
QTLUtils.h File Reference
#include <ctime>
#include <string>
#include <iostream>
#include <fstream>
#include <vector>
#include <Iterator>
#include <bitset>
#include <math.h>
Macros
#define SECOND_TO_MS 1000
Typedefs
typedef double EXPData
Functions
string reorderStr (const string input)
double d2r (const double x)
double d2rKosambi (const double d)
double d2rHaldane (const double d)
float getTimeStamp ()
template<class Iterator >
double getAverage (const Iterator begin, const Iterator end)
template<class Iterator >
double getVariance (const Iterator begin, const Iterator end, const double average)
template<typename T >
void inputValueFromKeyboard (string variableName, T *variableValue)
int inputBooleanFromKeyboard (string info=NULL)
template<typename T >
void printVectorData (const vector< T > data, const string title=NULL)
template<typename T >
int readFile2Vector (string filename, vector< T > &data, const int size=0)
template<typename T >
void readFile2Matrix (const string filename, vector< vector< T > > &m)
Macro Definition Documentation
#define SECOND_TO_MS 1000
Definition at line 20 of file QTLUtils.h.
Referenced by getTimeStamp().
Typedef Documentation
typedef double EXPData
Definition at line 22 of file QTLUtils.h.
Function Documentation
double d2r (const double x)
作图函数，默认使用Haldane作图函数
Parameters
x 遗传距离
Returns
重组率
Definition at line 52 of file QTLUtils.cpp.
References d2rHaldane().
Referenced by intervalQTL().
double d2rHaldane (const double d)
Haldane作图函数
Parameters
d 遗传距离
Returns
重组率
Definition at line 34 of file QTLUtils.cpp.
Referenced by d2r().
double d2rKosambi (const double d)
Kosambi作图函数
Parameters
d 遗传距离
Returns
重组率
Definition at line 43 of file QTLUtils.cpp.
template<class Iterator > double getAverage (const Iterator begin, const Iterator end)
获取向量中一组的算术平均值
Parameters
begin 起始数据
end 结尾数据
Returns
算数平均值
Definition at line 54 of file QTLUtils.h.
Referenced by getVariance(), and initExpressData().
float getTimeStamp ()
获取系统时间的时间戳
Returns
距离上一个时间戳的时间差，单位毫秒
Definition at line 9 of file QTLUtils.cpp.
References SECOND_TO_MS.
Referenced by main().
template<class Iterator > double getVariance (const Iterator begin, const Iterator end, const double average)
获取方差
Parameters
begin 开始位置的游标
end 结束位置的游标
average 平均值，默认为0，视为自动计算
Returns
数组数据的方差
Definition at line 71 of file QTLUtils.h.
References getAverage().
Referenced by initExpressData().
int inputBooleanFromKeyboard (string info)
从键盘输入判断值，1为真，0为假
Parameters
info 提示信息
Returns
判断值
Definition at line 21 of file QTLUtils.cpp.
Referenced by mainQTL().
template<typename T > void inputValueFromKeyboard (string variableName, T * variableValue)
从键盘输入变量的值
Parameters
variableName 变量名
variableValue 变量值
Definition at line 97 of file QTLUtils.h.
Referenced by mainQTL().
template<typename T > void printVectorData (const vector< T > data, const string title = NULL)
Definition at line 110 of file QTLUtils.h.
Referenced by printExpressData(), printIntervalData(), and printParentGeneData().
template<typename T > void readFile2Matrix (const string filename, vector< vector< T > > & m)
从文件读入矩阵
Parameters
filename 文件名
m 矩阵
Returns
Definition at line 159 of file QTLUtils.h.
Referenced by initChildrenGeneData().
template<typename T > int readFile2Vector (string filename, vector< T > & data, const int size = 0)
从文件读入向量
Parameters
filename 文件名
data 向量数据
size 向量大小，默认0为自动根据
Returns
实际读入向量的大小
Definition at line 130 of file QTLUtils.h.
Referenced by initExpressData(), initIntervalData(), and initParentGeneData().
string reorderStr (const string input)
重排一个字符串内字符，如bdcae重排为abcde
Parameters
input 需要重排的字符串
Returns
Definition at line 69 of file QTLUtils.cpp.
Referenced by reorderGene().